# 28-APRIL-2021, preparing the 4 hosts with IPv4 addresses

- hosts: host1
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 address
      copy:
        src: /home/cumulus/ON-10/host1
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for host1
      shell: /sbin/ifreload -a
      
- hosts: host2
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 address
      copy:
        src: /home/cumulus/ON-10/host2
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for host2
      shell: /sbin/ifreload -a
          
- hosts: host3
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 address
      copy:
        src: /home/cumulus/ON-10/host3
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for host3
      shell: /sbin/ifreload -a
      
- hosts: host4
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 address
      copy:
        src: /home/cumulus/ON-10/host4
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for host4
      shell: /sbin/ifreload -a
      
      
